spring.application.name=category-service

#config client service
spring.config.import=configserver:http://localhost:9094
#spring.cloud.config.profile=default
#spring.cloud.config.profile=dev
spring.cloud.config.profile=qa