spring.application.name=category-service

#config client service
spring.config.import=configserver:http://localhost:9094
#spring.cloud.config.profile=default
#spring.cloud.config.profile=dev
spring.cloud.config.profile=default


#for rabbitmq
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest