#spring.application.name=quiz
#spring.data.mongodb.uri=mongodb://localhost:27017/test
#server.port=9092
#
## Debug logging
#logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
#logging.level.com.mongodb=DEBUG