spring.application.name=config server
server.port=9094


##kaha se lena hai config ye sirf class path ke liye hai.
#spring.cloud.config.server.native.search-locations=classpath:/config
#spring.profiles.active=native
#for eureka server

# for github.
spring.cloud.config.server.git.uri=https://github.com/sahilvishwakarma79222/backendXMicroserviceConfiguration
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.clone-on-start=true




eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/